name: Ping Render Bot

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping bot URL to keep awake
        run: curl -s ${{ secrets.RENDER_DEPLOY_HOOK }} || echo "Ping failed"
